input {
  beats {
    port => 5044
  }
}

filter {
  if [message] =~ "ERROR" {
    mutate { add_field => { "log_level" => "ERROR" } }
  } else if [message] =~ "WARN" {
    mutate { add_field => { "log_level" => "WARN" } }
  } else {
    mutate { add_field => { "log_level" => "INFO" } }
  }

  mutate {
    add_field => { "service_name" => "%{[container][name]}" }
  }

  date {
    match => [ "@timestamp", "ISO8601" ]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "logs-%{+YYYY.MM.dd}"
  }
}